### ISSUE TITLE
Unexpected indent, line 74, what is the proper way to setup?

### ISSUE THREAD

**Issue by akshayrdeodhar** [Pranav2612000/bookmark-and-summarize#1]
How to run this thing? I've set FLASK_APP=main, but I'm getting this:
```
  File "/home/akshay/Desktop/COEP/BTech/CBD/bookmark-and-summarize/main.py", line 75
    @app.route('/Home')
    ^
IndentationError: unexpected unindent
```

Also, are we going to use specific versions? I created a venv, but we better have compatible versions of libraries.

**Comment by vishal-pathare** [comment]
IT has been resolved, it was a syntax error
